version: 0.2
   
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java -version
      - gradle -version
      - yum -y groupinstall 'Development Tools'
      - yum -y install curl file git
      - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
      - mkdir ~/.linuxbrew/bin
      - ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
      - eval $(~/.linuxbrew/bin/brew shellenv)
      - brew install hugo
  build:
    commands:
      - hugo -d public 
      - hugo deploy --target=s3
artifacts:
  files:
    - 'public/*'
  name: concurrencyworkshop-$(date +%Y-%m-%d) 
   
